### ISSUE TITLE
Add an option to "Link" shuffles of MSUs

### ISSUE THREAD

**Issue by Alaszun** [MattEqualsCoder/MSURandomizer#38]
Add an option that works as follows: 

If enabled, when shuffling, always pick the MSU track for linked tracks together. For instance, have the Desert Palace music and the Desert Palace Boss music come from the same MSU Pack if this is enabled.

This way if you have MSUs that work thematically (for instance, 8-Bit Disney picks a different movie as inspiration for each dungeon), you get to keep the theming.

**Comment by MattEqualsCoder** [comment]
This functionality already exists actually, though it's only applied to some Super Metroid tracks at the moment. This is a good reminder of some things I need to adjust with it:

- [ ] Make sure it works with 3+ tracks for AT & GT
- [ ] Fix it to work with the continuous shuffle
- [ ] Add option (possibly bundle into a dropdown with the chaos mode from #34)
